alter table public.services
  add column if not exists category text,
  add column if not exists sort_order integer;

alter table public.formations
  add column if not exists sort_order integer;

delete from public.services;
insert into public.services (
  category,
  title,
  description,
  benefits,
  duration,
  price,
  icon_name,
  image_url,
  sort_order
) values
(
  'Offres du moment',
  'BROWLIFT & REHAUSSEMENT',
  'Soin duo pour discipliner les sourcils et ouvrir le regard avec une tenue elegante.',
  ARRAY['Offres du moment', '1h 10min', '70 €']::text[],
  '1h 10min',
  '70 €',
  'Sparkles',
  'category:Offres du moment',
  1
),
(
  'Offres du moment',
  'DUO BROWLIFT',
  'Prestation duo pour structurer les sourcils et leur donner un effet coiffe naturel.',
  ARRAY['Offres du moment', '45min', '70 €']::text[],
  '45min',
  '70 €',
  'Sparkles',
  'category:Offres du moment',
  2
),
(
  'Offres du moment',
  'DUO REHAUSSEMENT',
  'Prestation duo pour recourber les cils et agrandir le regard avec douceur.',
  ARRAY['Offres du moment', '45min', '70 €']::text[],
  '45min',
  '70 €',
  'Sparkles',
  'category:Offres du moment',
  3
),
(
  'Offres du moment',
  'DUO MODELAGE',
  'Modelage duo sur reservation telephonique pour partager un moment de detente.',
  ARRAY['Offres du moment', '50min', '100 €']::text[],
  '50min',
  '100 €',
  'Sparkles',
  'category:Offres du moment',
  4
),
(
  'Offres du moment',
  'HEAD SPA',
  'Rituel bien-etre du cuir chevelu avec vapeur, massage et relaxation profonde.',
  ARRAY['Offres du moment', '1h', '60 €']::text[],
  '1h',
  '60 €',
  'Sparkles',
  'category:Offres du moment',
  5
),
(
  'Beauté du regard',
  'Epilation Sourcils',
  'Nettoyage de ligne pour redessiner les sourcils avec precision.',
  ARRAY['Beauté du regard', '10min', '7 €']::text[],
  '10min',
  '7 €',
  'Sparkles',
  'category:Beauté du regard',
  6
),
(
  'Beauté du regard',
  'Restructuration du sourcils + teinture (sans épilations)',
  'Travail de structure et coloration pour intensifier la ligne des sourcils.',
  ARRAY['Beauté du regard', '30min', '25 €']::text[],
  '30min',
  '25 €',
  'Sparkles',
  'category:Beauté du regard',
  7
),
(
  'Beauté du regard',
  'Restructuration du sourcils + teinture & épilation',
  'Prestation complete pour redefinir, teinter et epiler les sourcils.',
  ARRAY['Beauté du regard', '30min', '25 €']::text[],
  '30min',
  '25 €',
  'Sparkles',
  'category:Beauté du regard',
  8
),
(
  'Beauté du regard',
  'Teinture Sourcils',
  'Coloration rapide pour donner plus de relief au regard.',
  ARRAY['Beauté du regard', '10min', '10 €']::text[],
  '10min',
  '10 €',
  'Sparkles',
  'category:Beauté du regard',
  9
),
(
  'Beauté du regard',
  'Teinture des Sourcils au Henné Végétal',
  'Teinture vegetale pour un rendu plus intense et structure.',
  ARRAY['Beauté du regard', '15min', '15 €']::text[],
  '15min',
  '15 €',
  'Sparkles',
  'category:Beauté du regard',
  10
),
(
  'Extension & pose de cils',
  'La Pure - Cil à Cil',
  'Pose cil a cil naturelle pour sublimer le regard sans effet surcharge.',
  ARRAY['Extension & pose de cils', '1h', '55 €']::text[],
  '1h',
  '55 €',
  'Sparkles',
  'category:Extension & pose de cils',
  11
),
(
  'Extension & pose de cils',
  'Remplissage 3 semaines - Cil à Cil',
  'Entretien de la pose cil a cil pour conserver une ligne harmonieuse.',
  ARRAY['Extension & pose de cils', '30min', '35 €']::text[],
  '30min',
  '35 €',
  'Sparkles',
  'category:Extension & pose de cils',
  12
),
(
  'Extension & pose de cils',
  'La Divine - YY',
  'Technique en Y pour un regard plus fourni avec un effet elegant et leger.',
  ARRAY['Extension & pose de cils', '1h', '55 €']::text[],
  '1h',
  '55 €',
  'Sparkles',
  'category:Extension & pose de cils',
  13
),
(
  'Extension & pose de cils',
  'Remplissage 3 semaines - YY',
  'Retouche de la pose YY apres trois semaines.',
  ARRAY['Extension & pose de cils', '30min', '35 €']::text[],
  '30min',
  '35 €',
  'Sparkles',
  'category:Extension & pose de cils',
  14
),
(
  'Extension & pose de cils',
  'L''Elégante - Mixte',
  'Pose mixte equilibree pour apporter structure, douceur et profondeur au regard.',
  ARRAY['Extension & pose de cils', '1h', '65 €']::text[],
  '1h',
  '65 €',
  'Sparkles',
  'category:Extension & pose de cils',
  15
),
(
  'Maquillage permanent & retouches',
  'Microblading',
  'Dermopigmentation pour creer un effet poil a poil naturel sur les sourcils.',
  ARRAY['Maquillage permanent & retouches', '1h 30min', '180 €']::text[],
  '1h 30min',
  '180 €',
  'Sparkles',
  'category:Maquillage permanent & retouches',
  16
),
(
  'Maquillage permanent & retouches',
  'Retouche microblading',
  'Retouche d entretien pour raviver et fixer le resultat du microblading.',
  ARRAY['Maquillage permanent & retouches', '1h', '70 €']::text[],
  '1h',
  '70 €',
  'Sparkles',
  'category:Maquillage permanent & retouches',
  17
),
(
  'Maquillage permanent & retouches',
  'Microshading',
  'Effet poudre sur les sourcils pour un rendu plus maquille et structure.',
  ARRAY['Maquillage permanent & retouches', '1h 30min', '180 €']::text[],
  '1h 30min',
  '180 €',
  'Sparkles',
  'category:Maquillage permanent & retouches',
  18
),
(
  'Maquillage permanent & retouches',
  'Retouche Microshading',
  'Retouche fixatrice obligatoire pour un resultat optimal.',
  ARRAY['Maquillage permanent & retouches', '1h', '70 €']::text[],
  '1h',
  '70 €',
  'Sparkles',
  'category:Maquillage permanent & retouches',
  19
),
(
  'Maquillage permanent & retouches',
  'Candy lips',
  'Pigmentation des levres pour rehausser la couleur et redefinir le contour.',
  ARRAY['Maquillage permanent & retouches', '1h 30min', '150 €']::text[],
  '1h 30min',
  '150 €',
  'Sparkles',
  'category:Maquillage permanent & retouches',
  20
),
(
  'Beauté des mains & ongles',
  'Manucure Tiède',
  'Limage, soin des cuticules, masque ou bain de paraffine et modelage nourrissant.',
  ARRAY['Beauté des mains & ongles', '30min', '28 €']::text[],
  '30min',
  '28 €',
  'Sparkles',
  'category:Beauté des mains & ongles',
  21
),
(
  'Beauté des mains & ongles',
  'Manucure simple',
  'Limage, soin des cuticules et huile reparatrice pour des mains nettes.',
  ARRAY['Beauté des mains & ongles', '15min', '15 €']::text[],
  '15min',
  '15 €',
  'Sparkles',
  'category:Beauté des mains & ongles',
  22
),
(
  'Beauté des mains & ongles',
  'Dépose de semi permanent mains + manucure simple',
  'Depose en douceur accompagnee d une manucure d entretien.',
  ARRAY['Beauté des mains & ongles', '15min', '15 €']::text[],
  '15min',
  '15 €',
  'Sparkles',
  'category:Beauté des mains & ongles',
  23
),
(
  'Beauté des mains & ongles',
  'Manucure avec pose de vernis semi-permanent couleur',
  'Pose semi permanente couleur pour des mains impeccables et brillantes.',
  ARRAY['Beauté des mains & ongles', '30min', '28 €']::text[],
  '30min',
  '28 €',
  'Sparkles',
  'category:Beauté des mains & ongles',
  24
),
(
  'Beauté des mains & ongles',
  'Manucure avec pose de vernis semi-permanent French',
  'Version french pour une finition chic et intemporelle.',
  ARRAY['Beauté des mains & ongles', '40min', '32 €']::text[],
  '40min',
  '32 €',
  'Sparkles',
  'category:Beauté des mains & ongles',
  25
),
(
  'Manucure japonaise',
  'Manucure japonaise',
  'Soin naturel prestige pour renforcer l ongle et lui rendre un eclat sain.',
  ARRAY['Manucure japonaise', '30min', '24 €']::text[],
  '30min',
  '24 €',
  'Sparkles',
  'category:Manucure japonaise',
  26
),
(
  'Beauté des pieds',
  'Spa beauté des pieds',
  'Bain des pieds, gommage, soin cuticules, calluspeeling et masque hydratant.',
  ARRAY['Beauté des pieds', '50min', '45 €']::text[],
  '50min',
  '45 €',
  'Wind',
  'category:Beauté des pieds',
  27
),
(
  'Beauté des pieds',
  'Beauté des pieds simple',
  'Limage, cuticules et huile pour une mise en beaute rapide des pieds.',
  ARRAY['Beauté des pieds', '15min', '10 €']::text[],
  '15min',
  '10 €',
  'Wind',
  'category:Beauté des pieds',
  28
),
(
  'Beauté des pieds',
  'Pose de vernis semi-permanent pieds',
  'Pose semi permanente pour une tenue durable et une finition nette.',
  ARRAY['Beauté des pieds', '30min', '20 €']::text[],
  '30min',
  '20 €',
  'Wind',
  'category:Beauté des pieds',
  29
),
(
  'Beauté des pieds',
  'Dépose semi permanent pieds + pose de semi',
  'Depose et nouvelle pose semi permanente dans le meme rendez-vous.',
  ARRAY['Beauté des pieds', '35min', '25 €']::text[],
  '35min',
  '25 €',
  'Wind',
  'category:Beauté des pieds',
  30
),
(
  'Beauté des pieds',
  'Dépose seule vernis semi-permanent pieds',
  'Depose douce du semi permanent sur les pieds.',
  ARRAY['Beauté des pieds', '15min', '7 €']::text[],
  '15min',
  '7 €',
  'Wind',
  'category:Beauté des pieds',
  31
),
(
  'Soins cheveux & lissages',
  'Gommage détoxication cuir chevelu',
  'Elimine les impuretes et active la micro-circulation pour une pousse saine.',
  ARRAY['Soins cheveux & lissages', '30min', '25 €']::text[],
  '30min',
  '25 €',
  'Scissors',
  'category:Soins cheveux & lissages',
  32
),
(
  'Soins cheveux & lissages',
  'Brushing',
  'Mise en forme sur cheveux propres pour des longueurs lisses et brillantes.',
  ARRAY['Soins cheveux & lissages', '40min', '20 €']::text[],
  '40min',
  '20 €',
  'Scissors',
  'category:Soins cheveux & lissages',
  33
),
(
  'Soins cheveux & lissages',
  'Shamp + soin + brushing',
  'Nettoyage doux, soin hydratant et coiffage pour une chevelure souple.',
  ARRAY['Soins cheveux & lissages', '45min', '28 €']::text[],
  '45min',
  '28 €',
  'Scissors',
  'category:Soins cheveux & lissages',
  34
),
(
  'Soins cheveux & lissages',
  'Soins en profondeur + Brushing',
  'Masque nourrissant intense qui repare et apporte de l eclat avant le brushing.',
  ARRAY['Soins cheveux & lissages', '1h', '45 €']::text[],
  '1h',
  '45 €',
  'Scissors',
  'category:Soins cheveux & lissages',
  35
),
(
  'Soins cheveux & lissages',
  'Soin en profondeur',
  'Soin reconstructeur adapte a la fibre capillaire pour reparer durablement.',
  ARRAY['Soins cheveux & lissages', '2h', 'De 60 € à 80 €']::text[],
  '2h',
  'De 60 € à 80 €',
  'Scissors',
  'category:Soins cheveux & lissages',
  36
),
(
  'Soins cheveux & lissages',
  'Soins spécifiques Botox',
  'Traitement enrichi en proteines pour redonner force et volume.',
  ARRAY['Soins cheveux & lissages', '4h', 'De 60 € à 80 €']::text[],
  '4h',
  'De 60 € à 80 €',
  'Scissors',
  'category:Soins cheveux & lissages',
  37
),
(
  'Soins cheveux & lissages',
  'Soin cheveux blond aux ultrason réparation intense',
  'Hydrate en profondeur et lisse la fibre capillaire pour plus de brillance.',
  ARRAY['Soins cheveux & lissages', '2h', '70 €']::text[],
  '2h',
  '70 €',
  'Scissors',
  'category:Soins cheveux & lissages',
  38
),
(
  'Soins cheveux & lissages',
  'Soin profondeur aux ultrason',
  'Protege et reconstruit les cheveux fragilises ou colores.',
  ARRAY['Soins cheveux & lissages', '2h', '70 €']::text[],
  '2h',
  '70 €',
  'Scissors',
  'category:Soins cheveux & lissages',
  39
),
(
  'Soins cheveux & lissages',
  'Lissage indien protéiné',
  'Lissage doux riche en proteines pour renforcer et lisser en douceur.',
  ARRAY['Soins cheveux & lissages', '4h', 'De 90 € à 180 €']::text[],
  '4h',
  'De 90 € à 180 €',
  'Scissors',
  'category:Soins cheveux & lissages',
  40
),
(
  'Soins cheveux & lissages',
  'Lissage Tanin',
  'Formule aux tanins vegetaux pour discipliner et proteger la fibre.',
  ARRAY['Soins cheveux & lissages', '4h', 'De 90 € à 180 €']::text[],
  '4h',
  'De 90 € à 180 €',
  'Scissors',
  'category:Soins cheveux & lissages',
  41
),
(
  'Soins cheveux & lissages',
  'Lissage Brésilien',
  'Detend la fibre capillaire pour un effet lisse naturel longue duree.',
  ARRAY['Soins cheveux & lissages', '4h', 'De 90 € à 180 €']::text[],
  '4h',
  'De 90 € à 180 €',
  'Scissors',
  'category:Soins cheveux & lissages',
  42
),
(
  'Soins visage',
  'FLASH GLOW',
  'Nettoyage et exfoliation enzymatique avec infusion d un serum hydratant pour un coup d eclat express.',
  ARRAY['Soins visage', '20min', '35 €']::text[],
  '20min',
  '35 €',
  'Sparkles',
  'category:Soins visage',
  43
),
(
  'Soins visage',
  'PURE CLEAN T-ZONE',
  'Double nettoyage vapeur et extraction ciblee de la zone T avec serum purifiant.',
  ARRAY['Soins visage', '30min', '45 €']::text[],
  '30min',
  '45 €',
  'Sparkles',
  'category:Soins visage',
  44
),
(
  'Soins visage',
  'ECLAT JEUNESSE SUPRÊME',
  'Hydrafacial de base avec LED rouge et masque purifiant pour raffermir et illuminer.',
  ARRAY['Soins visage', '45min', '60 €']::text[],
  '45min',
  '60 €',
  'Sparkles',
  'category:Soins visage',
  45
),
(
  'Soins visage',
  'AQUA DETOX',
  'Hydrafacial de base avec LED bleue pour purifier les peaux sujettes aux imperfections.',
  ARRAY['Soins visage', '55min', '60 €']::text[],
  '55min',
  '60 €',
  'Sparkles',
  'category:Soins visage',
  46
),
(
  'Soins visage',
  'VITAMINE C RADIANCE',
  'HydraFacial enrichi en vitamine C pour uniformiser le teint et stimuler le collagene.',
  ARRAY['Soins visage', '1h', '75 €']::text[],
  '1h',
  '75 €',
  'Sparkles',
  'category:Soins visage',
  47
),
(
  'Soins visage',
  'LIFT ABSOLU',
  'Hydrafacial complet avec serums raffermissants et radiofrequence douce.',
  ARRAY['Soins visage', '1h', '70 €']::text[],
  '1h',
  '70 €',
  'Sparkles',
  'category:Soins visage',
  48
),
(
  'Soins visage',
  'SOIN DIAMANT',
  'Hydra et booster vitamine avec ultrason pour faire penetrer les actifs eclat.',
  ARRAY['Soins visage', '1h 10min', '75 €']::text[],
  '1h 10min',
  '75 €',
  'Sparkles',
  'category:Soins visage',
  49
),
(
  'Soins visage',
  'COLLAGEN BOOST',
  'Hydra, peel ajuste et radiofrequence pour stimuler la production de collagene.',
  ARRAY['Soins visage', '1h 20min', '85 €']::text[],
  '1h 20min',
  '85 €',
  'Sparkles',
  'category:Soins visage',
  50
),
(
  'Soins visage',
  'SIGNATURE LIFTING',
  'Hydra approfondi avec extractions, booster personnalise et microcourants.',
  ARRAY['Soins visage', '1h 30min', '110 €']::text[],
  '1h 30min',
  '110 €',
  'Sparkles',
  'category:Soins visage',
  51
),
(
  'Soins visage',
  'ROYAL MAISON DE SANEY',
  'Rituel d exception combinant hydrafacial complet et infusion d actifs premium.',
  ARRAY['Soins visage', '1h 40min', '120 €']::text[],
  '1h 40min',
  '120 €',
  'Sparkles',
  'category:Soins visage',
  52
),
(
  'Soins corps',
  'ÉVASION DOUCEUR',
  'Gommage delicat du corps suivi d un rincage relaxant pour une peau douce.',
  ARRAY['Soins corps', '45min', '60 €']::text[],
  '45min',
  '60 €',
  'Wind',
  'category:Soins corps',
  53
),
(
  'Soins corps',
  'RITUEL DÉTENTE & JACUZZI',
  'Gommage complet aux sels marins puis bain a remous pour relacher les tensions.',
  ARRAY['Soins corps', '1h', '75 €']::text[],
  '1h',
  '75 €',
  'Wind',
  'category:Soins corps',
  54
),
(
  'Soins corps',
  'GOMMAGE COCO VANILLE & JACUZZI',
  'Exfoliant gourmand coco-vanille puis jacuzzi pour nourrir et parfumer la peau.',
  ARRAY['Soins corps', '1h 15min', '80 €']::text[],
  '1h 15min',
  '80 €',
  'Wind',
  'category:Soins corps',
  55
),
(
  'Soins corps',
  'GOMMAGE DETOX SEL MARIN & JACUZZI',
  'Gommage aux sels marins et huiles essentielles suivi d un moment au jacuzzi.',
  ARRAY['Soins corps', '1h 15min', '85 €']::text[],
  '1h 15min',
  '85 €',
  'Wind',
  'category:Soins corps',
  56
),
(
  'Soins corps',
  'SIGNATURE MAISON DE SANEY',
  'Exfoliant aux huiles precieuses avec jacuzzi pour une peau satinee.',
  ARRAY['Soins corps', '1h 15min', '90 €']::text[],
  '1h 15min',
  '90 €',
  'Wind',
  'category:Soins corps',
  57
),
(
  'Soins corps',
  'GOMMAGE ROYAL JACUZZI + ENVELOPPEMENT',
  'Gommage complet, jacuzzi et massage corps complet pour une parenthese prestige.',
  ARRAY['Soins corps', '1h 30min', '100 €']::text[],
  '1h 30min',
  '100 €',
  'Wind',
  'category:Soins corps',
  58
),
(
  'Soins corps',
  'GOMMAGE SUPRÊME JACUZZI + MODELAGE',
  'Exfoliant integral, jacuzzi et modelage complet pour un lacher-prise total.',
  ARRAY['Soins corps', '1h 30min', '120 €']::text[],
  '1h 30min',
  '120 €',
  'Wind',
  'category:Soins corps',
  59
),
(
  'Microneedling',
  'MICRONEEDLING ACNÉ & TACHES',
  'Traite les cicatrices d acne, unifie le teint et attenue les taches pigmentaires.',
  ARRAY['Microneedling', '45min', '80 €']::text[],
  '45min',
  '80 €',
  'Syringe',
  'category:Microneedling',
  60
),
(
  'Microneedling',
  'CURE MICRONEEDLING ACNÉ & TACHES',
  'Cure de trois seances pour lisser les marques d acne et uniformiser le teint.',
  ARRAY['Microneedling', '45min', '210 €']::text[],
  '45min',
  '210 €',
  'Syringe',
  'category:Microneedling',
  61
),
(
  'Microneedling',
  'FLASH GLOW & MICRONEEDLING',
  'Association d un coup d eclat et d un microneedling pour preparer et booster la peau.',
  ARRAY['Microneedling', '1h 5min', '115 €']::text[],
  '1h 5min',
  '115 €',
  'Syringe',
  'category:Microneedling',
  62
),
(
  'Microneedling',
  'MICRONEEDLING RADIANCE',
  'Redonne eclat, luminosite et douceur aux teints ternes ou fatigues.',
  ARRAY['Microneedling', '45min', '100 €']::text[],
  '45min',
  '100 €',
  'Syringe',
  'category:Microneedling',
  63
),
(
  'Microneedling',
  'CURE MICRONEEDLING RADIANCE',
  'Cure de trois seances pour booster durablement l eclat du teint.',
  ARRAY['Microneedling', '45min', '255 €']::text[],
  '45min',
  '255 €',
  'Syringe',
  'category:Microneedling',
  64
),
(
  'Microneedling',
  'MICRONEEDLING ANTI-ÂGE / RAFFERMISSANT',
  'Lisse les rides, raffermit la peau et stimule la regeneration cellulaire.',
  ARRAY['Microneedling', '45min', '120 €']::text[],
  '45min',
  '120 €',
  'Syringe',
  'category:Microneedling',
  65
),
(
  'Microneedling',
  'CURE MICRONEEDLING ANTI-ÂGE / RAFFERMISSANT',
  'Cure dediee au raffermissement et a l amelioration de la texture cutanee.',
  ARRAY['Microneedling', '45min', '230 €']::text[],
  '45min',
  '230 €',
  'Syringe',
  'category:Microneedling',
  66
),
(
  'Microneedling',
  'MICRONEEDLING CUIR CHEVELU',
  'Active la microcirculation du cuir chevelu et stimule les follicules pour renforcer la repousse.',
  ARRAY['Microneedling', '1h', '90 €']::text[],
  '1h',
  '90 €',
  'Syringe',
  'category:Microneedling',
  67
),
(
  'Hollywood Peel / Carbon Peel',
  'Hollywood peel',
  'Soin visage au laser carbone pour illuminer le teint et resserrer les pores.',
  ARRAY['Hollywood Peel / Carbon Peel', '1h', '60 €']::text[],
  '1h',
  '60 €',
  'Syringe',
  'category:Hollywood Peel / Carbon Peel',
  68
),
(
  'Hollywood Peel / Carbon Peel',
  'Hollywood peel 3 séances',
  'Cure de trois seances pour un travail plus approfondi sur l eclat et les taches.',
  ARRAY['Hollywood Peel / Carbon Peel', '1h', '150 €']::text[],
  '1h',
  '150 €',
  'Syringe',
  'category:Hollywood Peel / Carbon Peel',
  69
),
(
  'Hollywood Peel / Carbon Peel',
  'Hollywood peel séances payées',
  'Rendez-vous de suivi pour les clientes deja engagees dans une cure.',
  ARRAY['Hollywood Peel / Carbon Peel', '1h', 'Sur devis']::text[],
  '1h',
  'Sur devis',
  'Syringe',
  'category:Hollywood Peel / Carbon Peel',
  70
),
(
  'Peeling aux algues',
  'Visage',
  'Peeling aux algues Zena pour eclaircir, nettoyer et resserrer les pores.',
  ARRAY['Peeling aux algues', '45min', '80 €']::text[],
  '45min',
  '80 €',
  'Syringe',
  'category:Peeling aux algues',
  71
),
(
  'Peeling aux algues',
  'Aisselles Foncées',
  'Soin cible pour attenuer les zones sombres sous les aisselles.',
  ARRAY['Peeling aux algues', '40min', '60 €']::text[],
  '40min',
  '60 €',
  'Syringe',
  'category:Peeling aux algues',
  72
),
(
  'Peeling aux algues',
  'Ventre',
  'Peeling corps pour lisser et clarifier la peau du ventre.',
  ARRAY['Peeling aux algues', '1h', '70 €']::text[],
  '1h',
  '70 €',
  'Syringe',
  'category:Peeling aux algues',
  73
),
(
  'Peeling aux algues',
  'Hyperpigmentation Coude',
  'Soin localise pour eclaircir les coudes et lisser le grain de peau.',
  ARRAY['Peeling aux algues', '40min', '45 €']::text[],
  '40min',
  '45 €',
  'Syringe',
  'category:Peeling aux algues',
  74
),
(
  'Peeling aux algues',
  'Dos',
  'Traitement exfoliant du dos pour purifier et unifier.',
  ARRAY['Peeling aux algues', '1h', '90 €']::text[],
  '1h',
  '90 €',
  'Syringe',
  'category:Peeling aux algues',
  75
),
(
  'Peeling aux algues',
  'Hyperpigmentation Genoux',
  'Peeling local pour attenuer les marques et zones plus foncees sur les genoux.',
  ARRAY['Peeling aux algues', '40min', '40 €']::text[],
  '40min',
  '40 €',
  'Syringe',
  'category:Peeling aux algues',
  76
),
(
  'Peeling aux algues',
  'Vergeture Cuisse',
  'Soin ciblant les vergetures sur les cuisses.',
  ARRAY['Peeling aux algues', '1h', '80 €']::text[],
  '1h',
  '80 €',
  'Syringe',
  'category:Peeling aux algues',
  77
),
(
  'Peeling aux algues',
  'Vergeture Fesse',
  'Traitement pour lisser l apparence des vergetures sur la zone des fesses.',
  ARRAY['Peeling aux algues', '45min', '60 €']::text[],
  '45min',
  '60 €',
  'Syringe',
  'category:Peeling aux algues',
  78
),
(
  'Hammam',
  'DOUCEUR - Solo (Accès hammam)',
  'Acces hammam solo pour une pause bien-etre chaleureuse.',
  ARRAY['Hammam', '1h 30min', '30 €']::text[],
  '1h 30min',
  '30 €',
  'Wind',
  'category:Hammam',
  79
),
(
  'Hammam',
  'DOUCEUR - Duo (Accès hammam)',
  'Acces hammam duo pour partager une experience de detente.',
  ARRAY['Hammam', '1h 30min', '42 €']::text[],
  '1h 30min',
  '42 €',
  'Wind',
  'category:Hammam',
  80
),
(
  'Hammam',
  'EVASION MAGIQUE - Solo',
  'Acces hammam et gommage au savon noir pour une peau purifiee.',
  ARRAY['Hammam', '1h 30min', '37 €']::text[],
  '1h 30min',
  '37 €',
  'Wind',
  'category:Hammam',
  81
),
(
  'Hammam',
  'EVASION MAGIQUE - Duo',
  'Version duo du rituel hammam et gommage au savon noir.',
  ARRAY['Hammam', '1h 30min', '56 €']::text[],
  '1h 30min',
  '56 €',
  'Wind',
  'category:Hammam',
  82
),
(
  'Hammam',
  'DÉTENTE DE FÉE - Solo',
  'Hammam, gommage au savon noir et enveloppement a l argile blanche.',
  ARRAY['Hammam', '1h 30min', '40 €']::text[],
  '1h 30min',
  '40 €',
  'Wind',
  'category:Hammam',
  83
),
(
  'Hammam',
  'DÉTENTE DE FÉE - Duo',
  'Version duo avec hammam, gommage et enveloppement a l argile blanche.',
  ARRAY['Hammam', '1h 30min', '60 €']::text[],
  '1h 30min',
  '60 €',
  'Wind',
  'category:Hammam',
  84
),
(
  'Hammam',
  'DOUCEUR - Solo accès hammam jacuzzi',
  'Version longue avec acces hammam prolonge.',
  ARRAY['Hammam', '2h', '46 €']::text[],
  '2h',
  '46 €',
  'Wind',
  'category:Hammam',
  85
),
(
  'Hammam',
  'DOUCEUR - Duo accès hammam jacuzzi',
  'Version duo longue pour profiter davantage de l espace detente.',
  ARRAY['Hammam', '2h', '58 €']::text[],
  '2h',
  '58 €',
  'Wind',
  'category:Hammam',
  86
),
(
  'Hammam',
  'ÉVASION MAGIQUE - Solo accès hammam jacuzzi',
  'Acces hammam et gommage au savon noir avec temps prolonge.',
  ARRAY['Hammam', '2h', '53 €']::text[],
  '2h',
  '53 €',
  'Wind',
  'category:Hammam',
  87
),
(
  'Hammam',
  'DÉTENTE PARTAGÉ',
  'Experience hammam privative sur devis, reservation par telephone.',
  ARRAY['Hammam', '2h', 'Sur devis']::text[],
  '2h',
  'Sur devis',
  'Wind',
  'category:Hammam',
  88
),
(
  'Hammam',
  'HARMONIE SPA Solo',
  'Acces hammam, gommage savon noir et massage du dos de 15 minutes.',
  ARRAY['Hammam', '2h', '79 €']::text[],
  '2h',
  '79 €',
  'Wind',
  'category:Hammam',
  89
),
(
  'Hammam',
  'TENUE TRADITIONNELLE HAMMAM POUR 7 PERSONNES À LOUER',
  'Location de tenue traditionnelle hammam pour groupe.',
  ARRAY['Hammam', '1h', '80 €']::text[],
  '1h',
  '80 €',
  'Wind',
  'category:Hammam',
  90
),
(
  'Hammam & Jacuzzi',
  'DOUCEUR - Solo (Accès hammam + Séance de jacuzzi)',
  'Acces hammam et seance de jacuzzi pour un moment solo relaxant.',
  ARRAY['Hammam & Jacuzzi', '1h 30min', '42 €']::text[],
  '1h 30min',
  '42 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  91
),
(
  'Hammam & Jacuzzi',
  'DOUCEUR - Duo (Accès hammam + Séance de jacuzzi)',
  'Acces hammam et jacuzzi en duo.',
  ARRAY['Hammam & Jacuzzi', '1h 30min', '52 €']::text[],
  '1h 30min',
  '52 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  92
),
(
  'Hammam & Jacuzzi',
  'EVASION MAGIQUE - Solo',
  'Hammam, jacuzzi et gommage au savon noir pour une peau neuve.',
  ARRAY['Hammam & Jacuzzi', '1h 30min', '52 €']::text[],
  '1h 30min',
  '52 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  93
),
(
  'Hammam & Jacuzzi',
  'EVASION MAGIQUE - Duo',
  'Rituel duo avec hammam, jacuzzi et gommage au savon noir.',
  ARRAY['Hammam & Jacuzzi', '1h 30min', '66 €']::text[],
  '1h 30min',
  '66 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  94
),
(
  'Hammam & Jacuzzi',
  'DÉTENTE DE FÉE - Solo',
  'Hammam, jacuzzi, gommage au savon noir et enveloppement a l argile blanche.',
  ARRAY['Hammam & Jacuzzi', '1h 30min', '62 €']::text[],
  '1h 30min',
  '62 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  95
),
(
  'Hammam & Jacuzzi',
  'DÉTENTE DE FÉE - Duo',
  'Version duo de la formule complete avec enveloppement a l argile blanche.',
  ARRAY['Hammam & Jacuzzi', '1h 30min', '76 €']::text[],
  '1h 30min',
  '76 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  96
),
(
  'Hammam & Jacuzzi',
  'DOUCEUR - Solo accès hammam jacuzzi',
  'Version longue de l acces hammam et jacuzzi en solo.',
  ARRAY['Hammam & Jacuzzi', '2h', '58 €']::text[],
  '2h',
  '58 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  97
),
(
  'Hammam & Jacuzzi',
  'DOUCEUR - Duo accès hammam jacuzzi',
  'Version duo prolongee avec hammam et jacuzzi.',
  ARRAY['Hammam & Jacuzzi', '2h', '68 €']::text[],
  '2h',
  '68 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  98
),
(
  'Hammam & Jacuzzi',
  'EVASION MAGIQUE - Solo accès hammam jacuzzi',
  'Formule longue avec hammam, jacuzzi et gommage au savon noir.',
  ARRAY['Hammam & Jacuzzi', '2h', '68 €']::text[],
  '2h',
  '68 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  99
),
(
  'Hammam & Jacuzzi',
  'EVASION MAGIQUE - Duo accès hammam jacuzzi',
  'Formule duo longue avec hammam, jacuzzi et gommage.',
  ARRAY['Hammam & Jacuzzi', '2h', '79 €']::text[],
  '2h',
  '79 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  100
),
(
  'Hammam & Jacuzzi',
  'DÉTENTE DE FÉE - Solo accès hammam jacuzzi',
  'Formule longue solo avec hammam, jacuzzi, gommage et enveloppement.',
  ARRAY['Hammam & Jacuzzi', '2h', '78 €']::text[],
  '2h',
  '78 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  101
),
(
  'Hammam & Jacuzzi',
  'HARMONIE SPA - Duo',
  'Hammam, jacuzzi, gommage savon noir et massage du dos de 15 minutes.',
  ARRAY['Hammam & Jacuzzi', '2h', '104 €']::text[],
  '2h',
  '104 €',
  'Wind',
  'category:Hammam & Jacuzzi',
  102
),
(
  'Head Spa',
  'HEAD SPA ESSENTIEL',
  'Rituel relaxant avec massage du cuir chevelu et vapeur douce pour liberer les tensions.',
  ARRAY['Head Spa', '45min', '60 €']::text[],
  '45min',
  '60 €',
  'Wind',
  'category:Head Spa',
  103
),
(
  'Head Spa',
  'HEAD SPA DETOX PURIFIANT',
  'Soin purifiant avec exfoliation, vapeur chaude et massage regenerant.',
  ARRAY['Head Spa', '1h', '75 €']::text[],
  '1h',
  '75 €',
  'Wind',
  'category:Head Spa',
  104
),
(
  'Head Spa',
  'HEAD SPA SIGNATURE',
  'Rituel complet incluant vapeur, serum nourrissant et massage japonais.',
  ARRAY['Head Spa', '1h 15min', '75 €']::text[],
  '1h 15min',
  '75 €',
  'Wind',
  'category:Head Spa',
  105
),
(
  'Head Spa',
  'HEAD SPA SIGNATURE SANEY',
  'Experience premium avec soins haut de gamme et massage exclusif du cuir chevelu.',
  ARRAY['Head Spa', '1h 30min', '120 €']::text[],
  '1h 30min',
  '120 €',
  'Wind',
  'category:Head Spa',
  106
),
(
  'Modelage & détente',
  'ÉCLAT EXPRESSE',
  'Modelage visage, nuque et cuir chevelu pour relacher les tensions et raviver le teint.',
  ARRAY['Modelage & détente', '30min', '30 €']::text[],
  '30min',
  '30 €',
  'Wind',
  'category:Modelage & détente',
  107
),
(
  'Modelage & détente',
  'DOUX ÉVEIL',
  'Modelage du dos, de la nuque et des bras pour une relaxation rapide.',
  ARRAY['Modelage & détente', '45min', '45 €']::text[],
  '45min',
  '45 €',
  'Wind',
  'category:Modelage & détente',
  108
),
(
  'Modelage & détente',
  'SIGNATURE MAISON',
  'Modelage complet corps et visage aux huiles chaudes pour une detente absolue.',
  ARRAY['Modelage & détente', '1h', '60 €']::text[],
  '1h',
  '60 €',
  'Wind',
  'category:Modelage & détente',
  109
),
(
  'Modelage & détente',
  'VOYAGE ORIENTALE',
  'Modelage inspire du rituel marocain a l huile d argan.',
  ARRAY['Modelage & détente', '1h', '70 €']::text[],
  '1h',
  '70 €',
  'Wind',
  'category:Modelage & détente',
  110
),
(
  'Modelage & détente',
  'CANDLE DREAM',
  'Modelage du corps a la bougie chaude transformee en huile nourrissante.',
  ARRAY['Modelage & détente', '1h', '90 €']::text[],
  '1h',
  '90 €',
  'Wind',
  'category:Modelage & détente',
  111
),
(
  'Modelage & détente',
  'ZEN ABSOLU',
  'Modelage relaxant de la tete aux pieds pour apaiser corps et esprit.',
  ARRAY['Modelage & détente', '1h 15min', '95 €']::text[],
  '1h 15min',
  '95 €',
  'Wind',
  'category:Modelage & détente',
  112
),
(
  'Modelage & détente',
  'RITUEL PRESTIGE',
  'Modelage complet aux huiles precieuses pour une detente profonde.',
  ARRAY['Modelage & détente', '1h 15min', '110 €']::text[],
  '1h 15min',
  '110 €',
  'Wind',
  'category:Modelage & détente',
  113
),
(
  'Épilations cire femme',
  'AISSELLES + DEMI JAMBES + MAILLOT INTEGRAL',
  'Forfait epilation cire pour les zones les plus demandees.',
  ARRAY['Épilations cire femme', '1h', '48 €']::text[],
  '1h',
  '48 €',
  'Scissors',
  'category:Épilations cire femme',
  114
),
(
  'Épilations cire femme',
  'AISSELLES + JAMBES ENTIERE + MAILLOT INTEGRAL',
  'Forfait complet jambes entieres, aisselles et maillot integral.',
  ARRAY['Épilations cire femme', '1h', '55 €']::text[],
  '1h',
  '55 €',
  'Scissors',
  'category:Épilations cire femme',
  115
),
(
  'Épilations cire femme',
  'EPILATIONS CORPS ENTIERS',
  'Forfait corps entier a prix avantageux.',
  ARRAY['Épilations cire femme', '2h', '115 €']::text[],
  '2h',
  '115 €',
  'Scissors',
  'category:Épilations cire femme',
  116
),
(
  'Épilations cire femme',
  'Visage complet',
  'Sourcils, levre et menton pour un visage net et harmonieux.',
  ARRAY['Épilations cire femme', '20min', '20 €']::text[],
  '20min',
  '20 €',
  'Scissors',
  'category:Épilations cire femme',
  117
),
(
  'Épilations cire femme',
  'Création ligne sourcils',
  'Creation ou restructuration de la ligne des sourcils a la cire.',
  ARRAY['Épilations cire femme', '20min', '15 €']::text[],
  '20min',
  '15 €',
  'Scissors',
  'category:Épilations cire femme',
  118
),
(
  'Épilations cire femme',
  'Entretien Sourcils',
  'Entretien regulier de la ligne des sourcils.',
  ARRAY['Épilations cire femme', '10min', '7 €']::text[],
  '10min',
  '7 €',
  'Scissors',
  'category:Épilations cire femme',
  119
),
(
  'Épilations cire femme',
  'Sourcils + Lèvres',
  'Forfait duo du visage pour une finition propre et rapide.',
  ARRAY['Épilations cire femme', '15min', '12 €']::text[],
  '15min',
  '12 €',
  'Scissors',
  'category:Épilations cire femme',
  120
),
(
  'Épilations cire femme',
  'Lèvre',
  'Epilation precise de la levre.',
  ARRAY['Épilations cire femme', '10min', '5 €']::text[],
  '10min',
  '5 €',
  'Scissors',
  'category:Épilations cire femme',
  121
),
(
  'Épilations cire femme',
  'Menton',
  'Epilation rapide du menton.',
  ARRAY['Épilations cire femme', '10min', '5 €']::text[],
  '10min',
  '5 €',
  'Scissors',
  'category:Épilations cire femme',
  122
),
(
  'Épilations cire femme',
  'Aisselles',
  'Epilation des aisselles a la cire.',
  ARRAY['Épilations cire femme', '10min', '12 €']::text[],
  '10min',
  '12 €',
  'Scissors',
  'category:Épilations cire femme',
  123
),
(
  'Épilations cire femme',
  '1/2 bras',
  'Epilation des demi-bras.',
  ARRAY['Épilations cire femme', '20min', '15 €']::text[],
  '20min',
  '15 €',
  'Scissors',
  'category:Épilations cire femme',
  124
),
(
  'Épilations cire femme',
  'Bras entiers',
  'Epilation complete des bras.',
  ARRAY['Épilations cire femme', '25min', '20 €']::text[],
  '25min',
  '20 €',
  'Scissors',
  'category:Épilations cire femme',
  125
),
(
  'Épilations cire femme',
  'Poitrine',
  'Epilation precise de la poitrine.',
  ARRAY['Épilations cire femme', '15min', '10 €']::text[],
  '15min',
  '10 €',
  'Scissors',
  'category:Épilations cire femme',
  126
),
(
  'Épilations cire femme',
  'Dos entier',
  'Epilation complete du dos.',
  ARRAY['Épilations cire femme', '30min', '20 €']::text[],
  '30min',
  '20 €',
  'Scissors',
  'category:Épilations cire femme',
  127
),
(
  'Épilations cire femme',
  'Ventre',
  'Epilation du ventre a la cire.',
  ARRAY['Épilations cire femme', '15min', '10 €']::text[],
  '15min',
  '10 €',
  'Scissors',
  'category:Épilations cire femme',
  128
),
(
  'Épilations cire femme',
  'Lombaires',
  'Epilation de la zone lombaire.',
  ARRAY['Épilations cire femme', '15min', '8 €']::text[],
  '15min',
  '8 €',
  'Scissors',
  'category:Épilations cire femme',
  129
),
(
  'Épilations cire femme',
  'Fesses',
  'Epilation de la zone des fesses.',
  ARRAY['Épilations cire femme', '10min', '7 €']::text[],
  '10min',
  '7 €',
  'Scissors',
  'category:Épilations cire femme',
  130
),
(
  'Épilations cire femme',
  'Maillot simple',
  'Epilation du maillot simple.',
  ARRAY['Épilations cire femme', '10min', '14 €']::text[],
  '10min',
  '14 €',
  'Scissors',
  'category:Épilations cire femme',
  131
),
(
  'Épilations cire femme',
  'Maillot échancré',
  'Epilation du maillot echancre.',
  ARRAY['Épilations cire femme', '20min', '20 €']::text[],
  '20min',
  '20 €',
  'Scissors',
  'category:Épilations cire femme',
  132
),
(
  'Épilations cire femme',
  'Maillot intégral',
  'Epilation du maillot integral.',
  ARRAY['Épilations cire femme', '30min', '24 €']::text[],
  '30min',
  '24 €',
  'Scissors',
  'category:Épilations cire femme',
  133
),
(
  'Épilations cire femme',
  '1/2 jambes',
  'Epilation des demi-jambes.',
  ARRAY['Épilations cire femme', '20min', '16 €']::text[],
  '20min',
  '16 €',
  'Scissors',
  'category:Épilations cire femme',
  134
),
(
  'Épilations cire femme',
  'Cuisses',
  'Epilation des cuisses.',
  ARRAY['Épilations cire femme', '20min', '16 €']::text[],
  '20min',
  '16 €',
  'Scissors',
  'category:Épilations cire femme',
  135
),
(
  'Épilations cire femme',
  'Jambes entières',
  'Epilation complete des jambes.',
  ARRAY['Épilations cire femme', '35min', '25 €']::text[],
  '35min',
  '25 €',
  'Scissors',
  'category:Épilations cire femme',
  136
),
(
  'Épilations définitive',
  'PROMOTION Formule Jambes Entières + Maillot Echancré + Aisselle',
  'Forfait laser promotionnel pour plusieurs zones corps.',
  ARRAY['Épilations définitive', '1h 30min', '126 €']::text[],
  '1h 30min',
  '126 €',
  'Scissors',
  'category:Épilations définitive',
  137
),
(
  'Épilations définitive',
  'PROMOTION Formule 1/2 Jambes + Maillot Intégral + Aisselle',
  'Forfait laser promotionnel multi-zones.',
  ARRAY['Épilations définitive', '1h 15min', '115,50 €']::text[],
  '1h 15min',
  '115,50 €',
  'Scissors',
  'category:Épilations définitive',
  138
),
(
  'Épilations définitive',
  'PROMOTION Formule Jambes Entières + Maillot Intégral + Aisselle',
  'Forfait laser promotionnel jambes entieres, maillot integral et aisselles.',
  ARRAY['Épilations définitive', '1h 30min', '147 €']::text[],
  '1h 30min',
  '147 €',
  'Scissors',
  'category:Épilations définitive',
  139
),
(
  'Épilations définitive',
  'Zone du visage',
  'Epilation definitive d une petite zone du visage.',
  ARRAY['Épilations définitive', '15min', '10,50 €']::text[],
  '15min',
  '10,50 €',
  'Scissors',
  'category:Épilations définitive',
  140
),
(
  'Épilations définitive',
  'Visage entier',
  'Traitement complet du visage.',
  ARRAY['Épilations définitive', '30min', '35 €']::text[],
  '30min',
  '35 €',
  'Scissors',
  'category:Épilations définitive',
  141
),
(
  'Épilations définitive',
  'Aisselles',
  'Laser zone aisselles.',
  ARRAY['Épilations définitive', '20min', '28 €']::text[],
  '20min',
  '28 €',
  'Scissors',
  'category:Épilations définitive',
  142
),
(
  'Épilations définitive',
  '1/2 bras',
  'Laser demi-bras.',
  ARRAY['Épilations définitive', '20min', '31,50 €']::text[],
  '20min',
  '31,50 €',
  'Scissors',
  'category:Épilations définitive',
  143
),
(
  'Épilations définitive',
  'Bras entiers',
  'Laser bras entiers.',
  ARRAY['Épilations définitive', '30min', '49 €']::text[],
  '30min',
  '49 €',
  'Scissors',
  'category:Épilations définitive',
  144
),
(
  'Épilations définitive',
  '1/2 jambes',
  'Laser demi-jambes.',
  ARRAY['Épilations définitive', '30min', '38,50 €']::text[],
  '30min',
  '38,50 €',
  'Scissors',
  'category:Épilations définitive',
  145
),
(
  'Épilations définitive',
  'Jambes entières',
  'Laser jambes entieres.',
  ARRAY['Épilations définitive', '45min', '70 €']::text[],
  '45min',
  '70 €',
  'Scissors',
  'category:Épilations définitive',
  146
),
(
  'Épilations définitive',
  'Bas du ventre',
  'Traitement laser du bas du ventre.',
  ARRAY['Épilations définitive', '20min', '28 €']::text[],
  '20min',
  '28 €',
  'Scissors',
  'category:Épilations définitive',
  147
),
(
  'Épilations définitive',
  'Dos entier',
  'Traitement laser du dos entier.',
  ARRAY['Épilations définitive', '30min', '49 €']::text[],
  '30min',
  '49 €',
  'Scissors',
  'category:Épilations définitive',
  148
),
(
  'Épilations définitive',
  'Maillot simple',
  'Laser maillot simple.',
  ARRAY['Épilations définitive', '15min', '21 €']::text[],
  '15min',
  '21 €',
  'Scissors',
  'category:Épilations définitive',
  149
),
(
  'Épilations définitive',
  'Maillot échancré',
  'Laser maillot echancre.',
  ARRAY['Épilations définitive', '15min', '28 €']::text[],
  '15min',
  '28 €',
  'Scissors',
  'category:Épilations définitive',
  150
),
(
  'Épilations définitive',
  'Maillot intégral',
  'Laser maillot integral.',
  ARRAY['Épilations définitive', '20min', '49 €']::text[],
  '20min',
  '49 €',
  'Scissors',
  'category:Épilations définitive',
  151
),
(
  'Blanchiment dentaire',
  'Blanchiment classique',
  'Soin blanchissant pour raviver l eclat du sourire.',
  ARRAY['Blanchiment dentaire', '1h', '50 €']::text[],
  '1h',
  '50 €',
  'Sparkles',
  'category:Blanchiment dentaire',
  152
),
(
  'Blanchiment dentaire',
  'Blanchiment +',
  'Version renforcee pour un resultat plus intense.',
  ARRAY['Blanchiment dentaire', '1h', '70 €']::text[],
  '1h',
  '70 €',
  'Sparkles',
  'category:Blanchiment dentaire',
  153
),
(
  'Détatouage',
  'Detatouages à partir de',
  'Seance de detatouage sur diagnostic, reservation par telephone.',
  ARRAY['Détatouage', '45min', '60 €']::text[],
  '45min',
  '60 €',
  'Syringe',
  'category:Détatouage',
  154
),
(
  'Détatouage',
  'Détatouage Sourcils',
  'Detatouage des sourcils sans perte de poils.',
  ARRAY['Détatouage', '30min', '60 €']::text[],
  '30min',
  '60 €',
  'Syringe',
  'category:Détatouage',
  155
),
(
  'Détatouage',
  'Détatouage grain de beauté',
  'Correction precise sur petite zone pigmentee.',
  ARRAY['Détatouage', '20min', '20 €']::text[],
  '20min',
  '20 €',
  'Syringe',
  'category:Détatouage',
  156
),
(
  'Détatouage',
  'Détatouage taches de rousseur',
  'Traitement laser pour attenuer les taches de rousseur tatouees.',
  ARRAY['Détatouage', '40min', '65 €']::text[],
  '40min',
  '65 €',
  'Syringe',
  'category:Détatouage',
  157
),
(
  'Détatouage',
  'Grand tatouages',
  'Detatouage de grandes zones, sur reservation telephonique.',
  ARRAY['Détatouage', '1h', '100 €']::text[],
  '1h',
  '100 €',
  'Syringe',
  'category:Détatouage',
  158
),
(
  'Kids Spa Premium',
  'DUO BAIN RELAX',
  'Bain moussant parfume, massage doux relaxant et boisson.',
  ARRAY['Kids Spa Premium', '30min', '25 €']::text[],
  '30min',
  '25 €',
  'Sparkles',
  'category:Kids Spa Premium',
  159
),
(
  'Kids Spa Premium',
  'DUO SPA DÉCOUVERTE',
  'Soin visage fruite, modelage des mains et photo souvenir.',
  ARRAY['Kids Spa Premium', '45min', '50 €']::text[],
  '45min',
  '50 €',
  'Sparkles',
  'category:Kids Spa Premium',
  160
),
(
  'Kids Spa Premium',
  'MINI BEAUTÉ (DUO)',
  'Pose de vernis classique, modelage des mains, boisson et gouter.',
  ARRAY['Kids Spa Premium', '35min', '40 €']::text[],
  '35min',
  '40 €',
  'Sparkles',
  'category:Kids Spa Premium',
  161
),
(
  'Kids Spa Premium',
  'SPA PRINCESSE DUO',
  'Modelage, soin visage et vernis classique mains et pieds.',
  ARRAY['Kids Spa Premium', '1h', '70 €']::text[],
  '1h',
  '70 €',
  'Sparkles',
  'category:Kids Spa Premium',
  162
),
(
  'Kids Spa Premium',
  'DUO RITUEL COCOON',
  'Bain, gommage des pieds, modelage relaxant et brushing.',
  ARRAY['Kids Spa Premium', '1h 20min', '80 €']::text[],
  '1h 20min',
  '80 €',
  'Sparkles',
  'category:Kids Spa Premium',
  163
),
(
  'Kids Spa Premium',
  'SOINS MÈRE & PETITE FILLE',
  'Moment complice a deux pour se detendre et se faire chouchouter.',
  ARRAY['Kids Spa Premium', '1h 20min', '85 €']::text[],
  '1h 20min',
  '85 €',
  'Sparkles',
  'category:Kids Spa Premium',
  164
),
(
  'Kids Spa Premium',
  'HAPPY BIRTHDAY BEAUTÉ',
  'Anniversaire beaute a partager entre enfants.',
  ARRAY['Kids Spa Premium', '3h', 'De 100 € à 140 €']::text[],
  '3h',
  'De 100 € à 140 €',
  'Sparkles',
  'category:Kids Spa Premium',
  165
),
(
  'Forfait mariée / fiancée',
  'Belle Jour J Signature',
  'Epilation complete, soin visage hydraskin, vernis semi pieds et mains, blanchiment classique et massage dos.',
  ARRAY['Forfait mariée / fiancée', '4h 50min', '190 €']::text[],
  '4h 50min',
  '190 €',
  'Sparkles',
  'category:Forfait mariée / fiancée',
  166
),
(
  'Forfait mariée / fiancée',
  'Belle Jour J Prestige',
  'Epilation complete, soin visage purifiant hydraskin, spa pieds, spa manucure, blanchiment et massage complet.',
  ARRAY['Forfait mariée / fiancée', '6h 40min', '290 €']::text[],
  '6h 40min',
  '290 €',
  'Sparkles',
  'category:Forfait mariée / fiancée',
  167
),
(
  'Carte cadeaux',
  'PLAISIR D''OFFRIR',
  'Carte cadeau valable sur toutes les prestations, a definir directement avec l institut.',
  ARRAY['Carte cadeaux', '1min', 'De 30 € à 200 €']::text[],
  '1min',
  'De 30 € à 200 €',
  'Sparkles',
  'category:Carte cadeaux',
  168
);

delete from public.formations;
insert into public.formations (
  title,
  description,
  price,
  duration,
  image_url,
  program,
  sort_order
) values
(
  'BLANCHIMENT DENTAIRE',
  'Formation intensive pour maitriser un protocole de blanchiment dentaire professionnel et proposer une prestation rentable des le lendemain.',
  600,
  '7h',
  'category:formations',
  ARRAY['Bases d hygiene', 'Protocoles complets', 'Conseils clientes']::text[],
  1
),
(
  'HYDRAFACIAL',
  'Formation pratique pour apprendre le deroule complet d un soin hydrafacial, le diagnostic de peau et les adaptations selon les besoins.',
  700,
  '7h',
  'category:formations',
  ARRAY['Diagnostic cutane', 'Utilisation de la machine', 'Protocoles eclat et detox']::text[],
  2
),
(
  'MICRONEEDLING',
  'Formation dediee aux techniques de microneedling visage et cuir chevelu avec securite, indications et accompagnement client.',
  600,
  '7h',
  'category:formations',
  ARRAY['Regles d hygiene', 'Gestes techniques', 'Choix des actifs']::text[],
  3
),
(
  'BROWLIFT',
  'Module court pour apprendre la discipline des sourcils, la mise en forme et le resultat salon immediat.',
  300,
  '6h',
  'category:formations',
  ARRAY['Analyse du sourcil', 'Application produit', 'Finition et conseils']::text[],
  4
),
(
  'REHAUSSEMENT DE CILS',
  'Formation pour maitriser le rehaussement de cils, le placement et la tenue du resultat.',
  300,
  '4h',
  'category:formations',
  ARRAY['Choix des pads', 'Mise en courbure', 'Tenue et entretien']::text[],
  5
),
(
  'REHAUSSEMENT DE CILS + BROWLIFT',
  'Parcours combine pour proposer deux prestations regard complementaires dans une meme formation.',
  500,
  '6h',
  'category:formations',
  ARRAY['Rehaussement', 'Browlift', 'Protocoles de vente']::text[],
  6
),
(
  'Cils à cils',
  'Formation extension cil a cil pour creer un regard naturel et maitriser les remplissages.',
  300,
  '6h',
  'category:formations',
  ARRAY['Isolation', 'Pose complete', 'Remplissage']::text[],
  7
),
(
  'Volume Mixte',
  'Formation destinee a creer un regard plus fourni avec un bon equilibre entre naturel et densite.',
  300,
  '6h',
  'category:formations',
  ARRAY['Bouquets legers', 'Mapping', 'Mix des techniques']::text[],
  8
),
(
  'Cils à cils + mixte + volume russe',
  'Formation longue couvrant les trois niveaux de pose d extensions de cils.',
  800,
  '12h',
  'category:formations',
  ARRAY['Cil a cil', 'Pose mixte', 'Volume russe']::text[],
  9
),
(
  'TOUT TYPES DE LISSAGE',
  'Formation dediee aux lissages les plus demandes pour adapter le protocole selon la nature du cheveu.',
  400,
  '7h',
  'category:formations',
  ARRAY['Diagnostic capillaire', 'Choix du lissage', 'Application et entretien']::text[],
  10
),
(
  'ÉPILATION CORPS ENTIER À LA CIRE',
  'Formation pratique pour realiser des epilations corps complet avec rapidite, hygiene et confort client.',
  300,
  '6h',
  'category:formations',
  ARRAY['Preparation de peau', 'Gestes pro', 'Confort cliente']::text[],
  11
),
(
  'PROTHÉSISTE ONGULAIRE',
  'Formation complete pour demarrer en onglerie avec preparation, construction et finitions modernes.',
  300,
  '6h',
  'category:formations',
  ARRAY['Preparation', 'Construction', 'Finition salon']::text[],
  12
);
